favoritecolor = input("Please type your favorite color:")
print("\n")
print("Your favorite color is", favoritecolor)
print("\n")
favoriteanimal = input("Please type your favorite animal:")
print("\n")
print("Your favorite animal is a", favoriteanimal)
print("\n")
favoritefood = input("Please type your favorite food:")
print("\n")
print("Your favorite food is", favoritefood)
print("\n")
favoritesport = input("Please type your favorite sport:")
print("\n")
print("Your favorite sport is", favoritesport)
print("\n")
favoritesibling = input("who is your favorite sibling?")
print()
print(f"Your favorite sibling is {favoritesibling}.")